apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-application.name" . }}-service
spec:
  type: ClusterIP
  selector:
{{ include "sample-application.labels" . | indent 4 }}
  ports:
    - port: {{ .Values.exposedPort }}
      name: my-exposed-port


